from django.db import models

class Commit(models.Model):
    pullID = models.IntegerField()
    sha = models.CharField(max_length = 200) # TODO more accurate max length?
    triggerTime = models.DateTimeField() # time of triggering event (e.g., commit, "bot:retest" comment) on GitHub
    # note: Django automatically creates Commit.resultset_set because ResultSet has a ForeignKey relation back to Commit
    
    def __unicode__(self):
        return "TODO" # TODO how to put Fields (esp. DateTimeField) into formatted string? How many characters from pullID and sha to include?
    
    
class ResultSet(models.Model):
    commit = models.ForeignKey(Commit)
    sourceID = models.CharField(max_length = 200) # TODO "
    timeReceived = models.DateTimeField()
    passed = models.BooleanField()
    # autogenerated: testresult_set
    rawResults = models.FileField() # TODO make private (how do in Python?) Is FileField best storage object available?
    
    def __unicode__(self):
        return "TODO" # TODO sourceID + timeReceived?
        
    
class TestResult(models.Model):
    resultSet = models.ForeignKey(ResultSet)
    passed = models.BooleanField()
    skipped = models.BooleanField()
    description = models.CharField(max_length = 200) # TODO "
    output = models.CharField(max_length = 200) # TODO "
    
    def __unicode__(self):
        return "TODO" # description or some placeholder if description is missing?
